name: Check Page

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分おきに実行
  workflow_dispatch:        # 手動実行も可

permissions:
  contents: write           # last_hash.txt をコミットするために必要

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}   # ← Secrets を環境変数に渡す
        run: python check_page.py

      - name: Save state (commit last_hash.txt)
        if: always()
        run: |
          if [ -f last_hash.txt ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_hash.txt
            git commit -m "chore: update last_hash" || echo "No changes to commit"
            git push
          fi
